[tool.poetry]
name = "parareq"
version = "0.1.0"
description = "Reliable Parallel OpenAI API Request Processing with Rate Limiting"
authors = ["Matt Gibson"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
